spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/question_card_db?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:quanshi666}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

minio:
  endpoint: ${MINIO_ENDPOINT:http://localhost:9150}
  access-key: ${MINIO_ACCESS_KEY:quanshi}
  secret-key: ${MINIO_SECRET_KEY:quanshi666}
  bucket-name: ${MINIO_BUCKET_NAME:question-card-images}

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET:your-secret-key-at-least-256-bits-long-for-HS256-algorithm}
  expiration: ${JWT_EXPIRATION:86400000}

volc:
  endpoint: ${VOLC_ENDPOINT:https://ark.cn-beijing.volces.com/api/v3}
  api-key: ${VOLC_API_KEY:}
  model-name: ${VOLC_MODEL_NAME:ep-20250124113936-hvfsw}

logging:
  level:
    com.knowledge.questioncard: INFO
    org.springframework.web: INFO
    org.hibernate: WARN
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'